// src/components/shared/Header.svelte
<!--
  Header Component - Site branding header
  Left: IssueFlow branding with version | Right: GitHub link
  Issue #190 - Redesign header and footer branding
  Uses UnoCSS utility classes for styling
-->

<script lang="ts">
  import { REPO_URL, COMPANY_SHORT } from '../../lib/footer-utils';

  const version: string = __APP_VERSION__;
</script>

<header
  class="w-full bg-slate-900 border-b border-slate-700/30 px-4 py-2 sticky top-0 z-50"
  aria-label="Site header"
>
  <div class="flex items-center justify-between max-w-6xl mx-auto gap-2 sm:gap-4">
    <!-- Left: Branding -->
    <div class="flex items-center gap-1 sm:gap-1.5">
      <span class="text-sm font-bold text-teal-300">IssueFlow</span>
      <span
        class="font-mono text-[0.5625rem] font-semibold text-teal-500 bg-teal-500/15 px-1 py-0.5 rounded-sm"
        >v{version}</span
      >
      <span class="text-[0.6875rem] text-slate-500 font-normal ml-1 hidden sm:inline"
        >Find your first contribution</span
      >
    </div>

    <!-- Right: GitHub link -->
    <nav class="flex items-center gap-0.5" aria-label="Header navigation">
      <a
        href={REPO_URL}
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1 px-1.5 sm:px-2 py-1 text-slate-400 no-underline text-[0.625rem] sm:text-[0.6875rem] font-medium rounded hover:text-teal-300 transition-colors duration-150 motion-reduce:transition-none"
      >
        <svg
          class="w-3.5 h-3.5 shrink-0"
          fill="currentColor"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path
            d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"
          />
        </svg>
        GitHub
      </a>
      <a
        href="{REPO_URL}/stargazers"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1 px-1.5 sm:px-2 py-1 text-slate-400 no-underline text-[0.625rem] sm:text-[0.6875rem] font-medium rounded hover:text-teal-300 transition-colors duration-150 motion-reduce:transition-none"
        aria-label="Star {COMPANY_SHORT} on GitHub"
      >
        <svg
          class="w-3 h-3 shrink-0"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"
          />
        </svg>
        Star
      </a>
    </nav>
  </div>
</header>

// src/components/landing/Header.tsx
import React, { useState, useEffect } from 'react';
import { siteConfig } from './config';
import { LogoIcon, GitHubIcon, MenuIcon, CloseIcon } from './icons';

const navLinks = [
  { text: 'Features', href: '#features' },
  { text: 'Use Cases', href: '#use-cases' },
  { text: 'Community', href: '#community' }
];

export function Header() {
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return (
    <header
      className="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
      style={{
        backgroundColor: scrolled ? 'oklch(0.98 0.004 264 / 0.8)' : 'transparent',
        backdropFilter: scrolled ? 'blur(12px) saturate(180%)' : 'none',
        borderBottom: scrolled ? '1px solid oklch(0.91 0.008 264 / 0.5)' : 'none'
      }}
    >
      <div
        className="dark:hidden"
        style={{
          position: 'absolute',
          inset: 0,
          backgroundColor: scrolled ? 'oklch(0.98 0.004 264 / 0.8)' : 'transparent',
          backdropFilter: scrolled ? 'blur(12px) saturate(180%)' : 'none'
        }}
      />
      <style>{`
        .dark header {
          background-color: ${scrolled ? 'oklch(0.1648 0.0075 270.93 / 0.8)' : 'transparent'} !important;
          border-bottom-color: ${scrolled ? 'oklch(0.3 0.01 264 / 0.5)' : 'transparent'} !important;
        }
      `}</style>
      <nav className="relative mx-auto flex max-w-[1000px] items-center justify-between px-4 py-3">
        <a href="/" className="flex items-center gap-2 z-10">
          <LogoIcon className="h-6 w-6 text-[oklch(0.78_0.13_291)]" />
          <span className="text-lg font-bold text-[oklch(0.15_0.02_264)] dark:text-[oklch(0.95_0.004_264)]">
            {siteConfig.name}
          </span>
        </a>

        <div className="hidden md:flex items-center gap-6">
          {navLinks.map((link) => (
            <a
              key={link.text}
              href={link.href}
              className="text-sm font-medium text-[oklch(0.52_0.01_264)] hover:text-[oklch(0.15_0.02_264)] dark:text-[oklch(0.7_0.01_264)] dark:hover:text-[oklch(0.95_0.004_264)] transition-colors"
            >
              {link.text}
            </a>
          ))}
          <a
            href={siteConfig.repo}
            target="_blank"
            rel="noopener noreferrer"
            className="text-[oklch(0.52_0.01_264)] hover:text-[oklch(0.15_0.02_264)] dark:text-[oklch(0.7_0.01_264)] dark:hover:text-[oklch(0.95_0.004_264)] transition-colors"
            aria-label="GitHub"
          >
            <GitHubIcon className="h-5 w-5" />
          </a>
          <a
            href="/app"
            className="rounded-lg px-4 py-2 text-sm font-medium text-white transition-colors"
            style={{ backgroundColor: 'oklch(0.78 0.13 291)' }}
          >
            Start Searching
          </a>
        </div>

        <button
          className="md:hidden z-10 text-[oklch(0.15_0.02_264)] dark:text-[oklch(0.95_0.004_264)]"
          onClick={() => setMobileOpen(!mobileOpen)}
          aria-label={mobileOpen ? 'Close menu' : 'Open menu'}
        >
          {mobileOpen ? <CloseIcon className="h-6 w-6" /> : <MenuIcon className="h-6 w-6" />}
        </button>

        {mobileOpen && (
          <div
            className="absolute top-full left-0 right-0 border-b py-4 px-4 md:hidden"
            style={{
              backgroundColor: 'oklch(0.98 0.004 264 / 0.95)',
              backdropFilter: 'blur(12px)',
              borderColor: 'oklch(0.91 0.008 264 / 0.5)'
            }}
          >
            <div className="flex flex-col gap-3">
              {navLinks.map((link) => (
                <a
                  key={link.text}
                  href={link.href}
                  onClick={() => setMobileOpen(false)}
                  className="text-sm font-medium py-2 text-[oklch(0.52_0.01_264)]"
                >
                  {link.text}
                </a>
              ))}
              <a
                href="/app"
                className="rounded-lg px-4 py-2 text-sm font-medium text-white text-center"
                style={{ backgroundColor: 'oklch(0.78 0.13 291)' }}
              >
                Start Searching
              </a>
            </div>
          </div>
        )}
      </nav>
    </header>
  );
}
