// src/components/landing/Hero.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { AuroraText } from './ui/aurora-text';
import { Section } from './Section';
import { siteConfig } from './config';
import { ArrowRightIcon } from './icons';

const ease = [0.16, 1, 0.3, 1] as const;

function HeroPill() {
  return (
    <motion.div
      className="flex items-center gap-2 rounded-full px-3 py-1 text-sm"
      style={{
        backgroundColor: 'oklch(0.78 0.13 291 / 0.15)',
        border: '1px solid oklch(0.78 0.13 291 / 0.3)'
      }}
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, ease }}
    >
      <span
        className="rounded-full px-2 py-0.5 text-xs font-medium text-white"
        style={{ backgroundColor: 'oklch(0.78 0.13 291)' }}
      >
        Open Source
      </span>
      <span className="text-[oklch(0.52_0.01_264)] dark:text-[oklch(0.7_0.01_264)]">
        Find beginner-friendly issues
      </span>
    </motion.div>
  );
}

function HeroTitles() {
  return (
    <div className="flex w-full max-w-3xl flex-col pt-8">
      <motion.h1
        className="text-4xl font-bold leading-tight tracking-tight sm:text-5xl md:text-6xl lg:text-7xl"
        initial={{ filter: 'blur(10px)', opacity: 0, y: 50 }}
        animate={{ filter: 'blur(0px)', opacity: 1, y: 0 }}
        transition={{ duration: 1, ease }}
      >
        <motion.span
          className="inline-block"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.5, ease }}
        >
          <AuroraText className="leading-normal font-bold">{siteConfig.hero.title}</AuroraText>
        </motion.span>
      </motion.h1>
      <motion.p
        className="mt-4 max-w-xl text-lg leading-relaxed text-[oklch(0.52_0.01_264)] dark:text-[oklch(0.7_0.01_264)]"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6, duration: 0.8, ease }}
      >
        {siteConfig.hero.description}
      </motion.p>
    </div>
  );
}

function HeroCTA() {
  return (
    <motion.div
      className="mt-8 flex flex-col sm:flex-row items-start gap-4"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.8, duration: 0.8, ease }}
    >
      <a
        href="/app"
        className="inline-flex items-center gap-2 rounded-lg px-6 py-3 text-base font-medium text-white transition-transform hover:scale-105"
        style={{ backgroundColor: 'oklch(0.78 0.13 291)' }}
      >
        {siteConfig.hero.cta}
        <ArrowRightIcon className="h-4 w-4" />
      </a>
      <a
        href={siteConfig.repo}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-2 rounded-lg border px-6 py-3 text-base font-medium transition-colors"
        style={{
          borderColor: 'oklch(0.91 0.008 264)',
          color: 'oklch(0.15 0.02 264)'
        }}
      >
        View on GitHub
      </a>
    </motion.div>
  );
}

function HeroVisual() {
  return (
    <motion.div
      className="relative hidden lg:flex items-center justify-center"
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ delay: 1, duration: 0.8, ease }}
    >
      <div
        className="relative w-80 rounded-xl border p-4 shadow-lg"
        style={{
          backgroundColor: 'oklch(0.98 0.004 264 / 0.9)',
          borderColor: 'oklch(0.91 0.008 264)',
          backdropFilter: 'blur(8px)'
        }}
      >
        <div
          className="flex items-center gap-2 mb-3 pb-3"
          style={{ borderBottom: '1px solid oklch(0.91 0.008 264)' }}
        >
          <div
            className="h-3 w-3 rounded-full"
            style={{ backgroundColor: 'oklch(0.68 0.15 15)' }}
          />
          <div
            className="h-3 w-3 rounded-full"
            style={{ backgroundColor: 'oklch(0.78 0.17 85)' }}
          />
          <div
            className="h-3 w-3 rounded-full"
            style={{ backgroundColor: 'oklch(0.68 0.17 145)' }}
          />
        </div>
        {[
          {
            label: 'good first issue',
            color: 'oklch(0.68 0.17 145)',
            title: 'Add dark mode toggle'
          },
          { label: 'help wanted', color: 'oklch(0.78 0.13 291)', title: 'Fix pagination logic' },
          { label: 'beginner', color: 'oklch(0.68 0.17 210)', title: 'Update README docs' }
        ].map((issue, i) => (
          <motion.div
            key={i}
            className="rounded-lg border p-3 mb-2 last:mb-0"
            style={{
              borderColor: 'oklch(0.91 0.008 264 / 0.7)',
              backgroundColor: 'oklch(0.96 0.004 264 / 0.5)'
            }}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 1.2 + i * 0.15, duration: 0.5, ease }}
          >
            <p className="text-sm font-medium text-[oklch(0.15_0.02_264)]">{issue.title}</p>
            <span
              className="mt-1 inline-block rounded-full px-2 py-0.5 text-xs font-medium text-white"
              style={{ backgroundColor: issue.color }}
            >
              {issue.label}
            </span>
          </motion.div>
        ))}
      </div>
    </motion.div>
  );
}

export function Hero() {
  return (
    <Section id="hero">
      <div className="relative grid grid-cols-1 lg:grid-cols-2 gap-8 w-full pt-24 pb-16 lg:pt-32 lg:pb-24">
        <div className="flex flex-col justify-start items-start">
          <HeroPill />
          <HeroTitles />
          <HeroCTA />
        </div>
        <HeroVisual />
      </div>
    </Section>
  );
}

// src/components/landing/Hero.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import AuroraText from './ui/AuroraText.svelte';
  import Section from './Section.svelte';
  import { siteConfig } from './config';

  let visible = $state(false);

  onMount(() => {
    requestAnimationFrame(() => (visible = true));
  });
</script>

<Section id="hero">
  <div class="hero-grid" class:visible>
    <div class="hero-content">
      <!-- Pill -->
      <div class="hero-pill anim-item" style="--delay: 0s;">
        <span class="pill-badge">Open Source</span>
        <span class="pill-text">Find beginner-friendly issues</span>
      </div>

      <!-- Title -->
      <h1 class="hero-title anim-item" style="--delay: 0.2s;">
        <AuroraText class="leading-normal font-bold">{siteConfig.hero.title}</AuroraText>
      </h1>

      <!-- Description -->
      <p class="hero-desc anim-item" style="--delay: 0.4s;">
        {siteConfig.hero.description}
      </p>

      <!-- CTA -->
      <div class="hero-cta anim-item" style="--delay: 0.6s;">
        <a href="/app" class="cta-primary">
          {siteConfig.hero.cta}
          <svg class="cta-arrow" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M17 8l4 4m0 0l-4 4m4-4H3"
            />
          </svg>
        </a>
        <a href={siteConfig.repo} target="_blank" rel="noopener noreferrer" class="cta-secondary">
          View on GitHub
        </a>
      </div>
    </div>

    <!-- Visual -->
    <div class="hero-visual anim-item" style="--delay: 0.8s;">
      <div class="visual-card">
        <div class="visual-dots">
          <span class="dot dot-red"></span>
          <span class="dot dot-yellow"></span>
          <span class="dot dot-green"></span>
        </div>
        {#each [{ label: 'good first issue', color: 'oklch(0.68 0.17 145)', title: 'Add dark mode toggle' }, { label: 'help wanted', color: 'var(--theme-accent)', title: 'Fix pagination logic' }, { label: 'beginner', color: 'oklch(0.68 0.17 210)', title: 'Update README docs' }] as issue, i (i)}
          <div class="visual-issue anim-item" style="--delay: {1 + i * 0.15}s;">
            <p class="visual-issue-title">{issue.title}</p>
            <span class="visual-issue-label" style="background-color: {issue.color};"
              >{issue.label}</span
            >
          </div>
        {/each}
      </div>
    </div>
  </div>
</Section>

<style>
  .hero-grid {
    position: relative;
    display: grid;
    grid-template-columns: 1fr;
    gap: 2rem;
    width: 100%;
    padding-top: 6rem;
    padding-bottom: 4rem;
  }

  @media (min-width: 1024px) {
    .hero-grid {
      grid-template-columns: 1fr 1fr;
      padding-top: 8rem;
      padding-bottom: 6rem;
    }
  }

  .hero-content {
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: flex-start;
  }

  /* Animation */
  .anim-item {
    opacity: 0;
    transform: translateY(20px);
    transition:
      opacity 0.8s cubic-bezier(0.16, 1, 0.3, 1),
      transform 0.8s cubic-bezier(0.16, 1, 0.3, 1);
    transition-delay: var(--delay, 0s);
  }

  .visible .anim-item {
    opacity: 1;
    transform: translateY(0);
  }

  /* Pill */
  .hero-pill {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    border-radius: 9999px;
    padding: 0.25rem 0.75rem;
    font-size: 0.875rem;
    background-color: oklch(from var(--theme-accent) l c h / 0.15);
    border: 1px solid oklch(from var(--theme-accent) l c h / 0.3);
  }

  .pill-badge {
    border-radius: 9999px;
    padding: 0.125rem 0.5rem;
    font-size: 0.75rem;
    font-weight: 500;
    color: white;
    background-color: var(--theme-accent);
  }

  .pill-text {
    color: var(--theme-text-muted);
  }

  /* Title */
  .hero-title {
    padding-top: 2rem;
    font-size: 2.25rem;
    font-weight: 700;
    line-height: 1.1;
    letter-spacing: -0.025em;
  }

  @media (min-width: 640px) {
    .hero-title {
      font-size: 3rem;
    }
  }
  @media (min-width: 768px) {
    .hero-title {
      font-size: 3.75rem;
    }
  }
  @media (min-width: 1024px) {
    .hero-title {
      font-size: 4.5rem;
    }
  }

  /* Description */
  .hero-desc {
    margin-top: 1rem;
    max-width: 36rem;
    font-size: 1.125rem;
    line-height: 1.75;
    color: var(--theme-text-muted);
  }

  /* CTA buttons */
  .hero-cta {
    margin-top: 2rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  @media (min-width: 640px) {
    .hero-cta {
      flex-direction: row;
      align-items: flex-start;
    }
  }

  .cta-primary {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    border-radius: 0.5rem;
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
    font-weight: 500;
    color: white;
    background-color: var(--theme-accent);
    text-decoration: none;
    transition: transform 0.15s ease;
  }

  .cta-primary:hover {
    transform: scale(1.05);
  }

  .cta-arrow {
    width: 1rem;
    height: 1rem;
  }

  .cta-secondary {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    border-radius: 0.5rem;
    border: 1px solid var(--theme-border);
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
    font-weight: 500;
    color: var(--theme-text-primary);
    text-decoration: none;
    transition: border-color 0.15s ease;
  }

  .cta-secondary:hover {
    border-color: var(--theme-accent);
  }

  /* Visual card */
  .hero-visual {
    display: none;
    align-items: center;
    justify-content: center;
  }

  @media (min-width: 1024px) {
    .hero-visual {
      display: flex;
    }
  }

  .visual-card {
    position: relative;
    width: 20rem;
    border-radius: 0.75rem;
    border: 1px solid var(--theme-border);
    padding: 1rem;
    background-color: var(--theme-bg-card, var(--theme-bg-secondary));
    box-shadow: 0 4px 24px var(--theme-shadow);
  }

  .visual-dots {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.75rem;
    padding-bottom: 0.75rem;
    border-bottom: 1px solid var(--theme-border);
  }

  .dot {
    width: 0.75rem;
    height: 0.75rem;
    border-radius: 50%;
  }

  .dot-red {
    background-color: oklch(0.68 0.15 15);
  }
  .dot-yellow {
    background-color: oklch(0.78 0.17 85);
  }
  .dot-green {
    background-color: oklch(0.68 0.17 145);
  }

  .visual-issue {
    border-radius: 0.5rem;
    border: 1px solid var(--theme-border);
    padding: 0.75rem;
    margin-bottom: 0.5rem;
    background: var(--theme-bg-tertiary);
  }

  .visual-issue:last-child {
    margin-bottom: 0;
  }

  .visual-issue-title {
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--theme-text-primary);
  }

  .visual-issue-label {
    display: inline-block;
    margin-top: 0.25rem;
    border-radius: 9999px;
    padding: 0.125rem 0.5rem;
    font-size: 0.75rem;
    font-weight: 500;
    color: white;
  }

  @media (prefers-reduced-motion: reduce) {
    .anim-item {
      opacity: 1;
      transform: none;
      transition: none;
    }
  }
</style>
