// src/components/landing/ui/aurora-text.tsx
import React, { memo } from 'react';

interface AuroraTextProps {
  children: React.ReactNode;
  className?: string;
  colors?: string[];
  speed?: number;
}

export const AuroraText = memo(function AuroraText({
  children,
  className = '',
  colors = ['#ef4444', '#a855f7', '#3b82f6', '#8b5cf6', '#f59e0b'],
  speed = 1
}: AuroraTextProps) {
  const gradientStyle: React.CSSProperties = {
    backgroundImage: `linear-gradient(135deg, ${colors.join(', ')}, ${colors[0]})`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    backgroundSize: '200% auto',
    animationName: 'aurora',
    animationDuration: `${10 / speed}s`,
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    animationDirection: 'alternate'
  };

  return (
    <span className={`relative inline-block ${className}`}>
      <span className="sr-only">{children}</span>
      <span style={gradientStyle} aria-hidden="true">
        {children}
      </span>
    </span>
  );
});

// src/components/landing/ui/AuroraText.svelte
<script lang="ts">
  interface Props {
    class?: string;
    colors?: string[];
    speed?: number;
  }

  let {
    class: className = '',
    colors = ['#ef4444', '#a855f7', '#3b82f6', '#8b5cf6', '#f59e0b'],
    speed = 1,
    children
  }: Props & { children?: any } = $props();

  const gradient = `linear-gradient(135deg, ${colors.join(', ')}, ${colors[0]})`;
  const duration = `${10 / speed}s`;
</script>

<span class="aurora-wrapper {className}">
  <span class="sr-only"><slot /></span>
  <span
    class="aurora-text"
    style="background-image: {gradient}; animation-duration: {duration};"
    aria-hidden="true"
  >
    <slot />
  </span>
</span>

<style>
  .aurora-wrapper {
    position: relative;
    display: inline-block;
  }

  .aurora-text {
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    background-size: 200% auto;
    animation-name: aurora;
    animation-timing-function: ease-in-out;
    animation-iteration-count: infinite;
    animation-direction: alternate;
  }
</style>
