// src/components/landing/ui/OrbitingCircles.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    class?: string;
    children?: Snippet;
    reverse?: boolean;
    duration?: number;
    delay?: number;
    radius?: number;
    path?: boolean;
  }

  let {
    class: className = '',
    children,
    reverse = false,
    duration = 20,
    delay = 10,
    radius = 50,
    path = true
  }: Props = $props();
</script>

{#if path}
  <svg xmlns="http://www.w3.org/2000/svg" class="orbit-path">
    <circle
      cx="50%"
      cy="50%"
      r={radius}
      fill="none"
      stroke="var(--theme-text-muted, oklch(0.52 0.01 264 / 0.2))"
      stroke-width="1"
    />
  </svg>
{/if}
<div
  class="orbit-item {className}"
  style="
    --radius: {radius};
    animation: orbit {duration}s linear infinite {reverse ? 'reverse' : 'normal'};
    animation-delay: {-delay}s;
  "
>
  {#if children}
    {@render children()}
  {/if}
</div>

<style>
  .orbit-path {
    pointer-events: none;
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
  }

  .orbit-item {
    position: absolute;
    display: flex;
    width: 2rem;
    height: 2rem;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    border: 1px solid var(--theme-border, oklch(0.82 0.008 264 / 0.2));
    background: var(--theme-bg-primary, oklch(0.98 0.004 264 / 0.05));
  }
</style>

// src/components/landing/ui/orbiting-circles.tsx
import React from 'react';

interface OrbitingCirclesProps {
  className?: string;
  children?: React.ReactNode;
  reverse?: boolean;
  duration?: number;
  delay?: number;
  radius?: number;
  path?: boolean;
}

export default function OrbitingCircles({
  className,
  children,
  reverse,
  duration = 20,
  delay = 10,
  radius = 50,
  path = true
}: OrbitingCirclesProps) {
  return (
    <>
      {path && (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="pointer-events-none absolute inset-0 w-full h-full"
        >
          <circle
            cx="50%"
            cy="50%"
            r={radius}
            fill="none"
            stroke="oklch(0.52 0.01 264 / 0.2)"
            strokeWidth="1"
          />
        </svg>
      )}
      <div
        style={
          {
            '--duration': `${duration}`,
            '--radius': `${radius}`,
            '--delay': `${-delay}`,
            animationName: 'orbit',
            animationDuration: `${duration}s`,
            animationTimingFunction: 'linear',
            animationIterationCount: 'infinite',
            animationDelay: `${-delay}s`,
            animationDirection: reverse ? 'reverse' : 'normal'
          } as React.CSSProperties
        }
        className={`absolute flex w-8 h-8 items-center justify-center rounded-full border border-gray-200/20 bg-white/5 dark:bg-white/10 ${className || ''}`}
      >
        {children}
      </div>
    </>
  );
}
